plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.4'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'jacoco'
}

group = 'ticket'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.redisson:redisson-spring-boot-starter:3.18.0'
	implementation 'io.hypersistence:hypersistence-utils-hibernate-63:3.7.6'
	testImplementation("junit:junit:4.13.2")
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.projectlombok:lombok:1.18.22'
	testImplementation 'io.rest-assured:rest-assured:5.1.1'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	runtimeOnly 'org.mariadb.jdbc:mariadb-java-client'
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	testCompileOnly 'org.projectlombok:lombok'
	testAnnotationProcessor 'org.projectlombok:lombok'
}

jacoco {
	toolVersion = "0.8.12"
}

test {
	useJUnitPlatform()
	jvmArgs "-Xshare:off"

	finalizedBy jacocoTestReport
	ignoreFailures = true

	testLogging {
		events "passed", "failed", "skipped"
		showStandardStreams = true
	}

	jacoco {
		excludes += [
				'app/ticket/StartApplication.class',
				'app/ticket/ticketing/common/*',
				'app/ticket/ticketing/redis/*'
		]
	}

	afterSuite { desc, result ->
		if (!desc.parent) { // 전체 테스트 요약
			def total = result.testCount
			def passed = result.successfulTestCount
			def failed = result.failedTestCount
			def skipped = result.skippedTestCount
			def rate = total > 0 ? (passed * 100 / total) : 0

			println "==============================="
			println " Test Summary"
			println "-------------------------------"
			println " Total:   $total"
			println " Passed:  $passed"
			println " Failed:  $failed"
			println " Skipped: $skipped"
			println "-------------------------------"
			println " Pass rate: ${rate}%"
			println "==============================="
		}
	}
}

jacocoTestReport {
	dependsOn test

	reports {
		csv.required = true
		html.required = true
		xml.required = true
	}

	afterEvaluate {
		classDirectories.setFrom(files(classDirectories.files.collect {
			fileTree(dir: it,
					exclude: ['app/ticket/StartApplication.class',
							  'app/ticket/ticketing/common/*',
							  'app/ticket/ticketing/redis/*'])
		}))
	}
}

jacocoTestCoverageVerification {
	violationRules {
		rule {
			limit {
				minimum = 0.95
			}
		}
	}
}