services:
  db:
    image: mariadb
    container_name: mariadb
    restart: always
    env_file: # 환경변수 파일
      - ./.env
    environment:
      TZ : "Asia/Seoul"
      MARIADB_USER: ${MARIADB_USER}
      MARIA_DB_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  server:
    build: ./   # 서버 소스코드 Dockerfile 경로
    container_name: server
    restart: always
    env_file: # 환경변수 파일
      - ./.env
    environment:
      spring.jpa.hibernate.ddl-auto: update
    ports:
      - "3000:3000"
    healthcheck:
      test: [ "CMD", "curl", "-fs", "http://server:3000/actuator/health"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    depends_on:
      db :
        condition: service_healthy

  server-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: server-test
    env_file: # 환경변수 파일
      - ./.env
    environment:
      spring.jpa.hibernate.ddl-auto: none
    depends_on:
      server:
        condition: service_healthy
    command: ["./gradlew", "clean", "test", "jacocoTestReport", "jacocoTestCoverageVerification", "checkstyleMain"]