spring.application.name=ticketing

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.properties.hibernate.transaction.jta.platform=org.hibernate.service.jta.JtaPlatform
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQLDialect

spring.datasource.url=${MARIADB_URL}
spring.datasource.username=${MARIADB_USER}
spring.datasource.password=${MARIADB_ROOT_PASSWORD}

environment.URL=${SERVER_URL}
server.port=${SERVER_PORT}