# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: CI - Workflow

on:
  pull_request:
    branches: [ "master", "dev", "feat/*" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Actions
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Docker Setup Compose
        uses: docker/setup-compose-action@v1.2.0

      - name: Create .env
        shell: bash
        run: |
          touch .env
          echo "${{secrets.APPLICATION_ENV}}" >> .env
          echo API_KEY="$ENV_API_KEY" >> .env
          cat .env

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image:latest

      - name: Run Docker Compose
        run: |
          docker compose down
          docker compose up --build --exit-code-from server-test

      - name: Copy JaCoCo report to host
        if: always()
        run: |
          mkdir -p reports
          docker compose cp server-test:/app/build/reports/jacoco/test/jacocoTestReport.xml ./reports/
          docker compose cp server-test:/app/build/reports/jacoco/test/html ./reports/html

      - name: Report test Coverage
        if: always()
        uses: madrapps/jacoco-report@v1.6.1
        with:
          title: 📝 Test Coverage Report
          paths: reports/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 95
          min-coverage-changed-files: 95
          update-comment: true
          debug-mode: true